"""таблицы юзер, сервер и домены

Revision ID: aa75331b98ca
Revises: 
Create Date: 2025-09-14 16:50:42.636879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa75331b98ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'WORKER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('hestia_username', sa.String(), nullable=False),
    sa.Column('hestia_password', sa.String(), nullable=True),
    sa.Column('FTP_username', sa.String(), nullable=False),
    sa.Column('FTP_password', sa.String(), nullable=True),
    sa.Column('namecheap_enabled', sa.Boolean(), nullable=False),
    sa.Column('namecheap_api_key', sa.String(), nullable=True),
    sa.Column('namecheap_api_user', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('server_provider', sa.Enum('VULTR', name='serverprovider'), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('server_ip', sa.String(), nullable=False),
    sa.Column('server_region', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('server_tag', sa.String(), nullable=True),
    sa.Column('server_password', sa.String(), nullable=True),
    sa.Column('server_status', sa.Enum('PENDING', 'ACTIVE', 'STOPED', 'DELETED', name='serverstatus'), nullable=False),
    sa.Column('hestia_installed', sa.Boolean(), nullable=False),
    sa.Column('hestia_url', sa.String(), nullable=True),
    sa.Column('FTP_installed', sa.Boolean(), nullable=False),
    sa.Column('max_domains', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id'),
    sa.UniqueConstraint('server_ip')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('domain_provider', sa.Enum('NAMECHEAP', name='domainprovider'), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('domain_status', sa.Enum('ACTIVE', 'DELETED', name='domainstatus'), nullable=False),
    sa.Column('ssl_activated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domains')
    op.drop_table('servers')
    op.drop_table('users')
    # ### end Alembic commands ###
